version: '2'
services:
    core:
        build: .
        image: aragon/core
        hostname: aragon-core
        ports:
         - "3000:3000"
        volumes:
        - ./docker_home:/root/
        - ./:/usr/src/app
        - /usr/src/app/node_modules
